// Code-node source for "HMZ - Reply Human Approval - Validation" (workflow 07).
// Each exported function returns the jsCode string for one n8n Code node.
// CONFIG is injected as a JSON literal by build-business-ready.mjs so the
// workflow carries the single durable non-secret configuration source
// (config/business-ready.config.json) without any external file read at
// runtime (n8n Code-node sandboxes do not reliably permit fs access).

const HELPERS = [
  'function djb2Hash(str) {',
  '  let hash = 5381;',
  '  for (let i = 0; i < str.length; i++) {',
  '    hash = (hash << 5) + hash + str.charCodeAt(i);',
  '    hash = hash & 0xffffffff;',
  '  }',
  '  return (hash >>> 0).toString(16).padStart(8, "0");',
  '}',
  '',
  'function randomHex(bytes) {',
  '  let out = "";',
  '  if (typeof globalThis.crypto !== "undefined" && typeof globalThis.crypto.getRandomValues === "function") {',
  '    const arr = new Uint8Array(bytes);',
  '    globalThis.crypto.getRandomValues(arr);',
  '    for (const b of arr) out += b.toString(16).padStart(2, "0");',
  '    return out;',
  '  }',
  '  for (let i = 0; i < bytes; i++) out += Math.floor(Math.random() * 256).toString(16).padStart(2, "0");',
  '  return out;',
  '}',
  '',
  'function generateReviewToken() {',
  '  return randomHex(16) + djb2Hash(String(Date.now()) + String(Math.random()));',
  '}',
  '',
  'function escapeHtml(value) {',
  '  return String(value == null ? "" : value)',
  '    .replace(/&/g, "&amp;")',
  '    .replace(/</g, "&lt;")',
  '    .replace(/>/g, "&gt;")',
  '    .replace(/"/g, "&quot;")',
  "    .replace(/'/g, '&#39;');",
  '}'
].join('\n');

export function nodeA_BuildReviewCase(configJson) {
  return [
    'const items = $input.all();',
    '',
    'const CONFIG = ' + configJson + ';',
    '',
    HELPERS,
    '',
    'return items.map(item => {',
    '  const input = item.json || {};',
    '  const caseInput = input.case_input || {};',
    '  const nes = caseInput.nes || {};',
    '  const decision = caseInput.decision || {};',
    '  const draft = caseInput.draft || {};',
    '  const reply = nes.reply || {};',
    '',
    '  const intakeId = String(caseInput.intake_id || nes.intake_id || "UNKNOWN_INTAKE");',
    '  const policyVersion = caseInput.policy_version || nes.policy_version || CONFIG.policy_version;',
    '  const caseId = "case-" + djb2Hash(intakeId + "|" + policyVersion);',
    '',
    '  const ttlRaw = CONFIG.review.review_token_ttl_minutes;',
    '  const ttlMinutes = (typeof ttlRaw === "number" && ttlRaw > 0) ? ttlRaw : CONFIG.review.review_token_ttl_minutes_default;',
    '',
    '  const nowIso = new Date().toISOString();',
    '  const expiresIso = new Date(Date.now() + ttlMinutes * 60000).toISOString();',
    '  const token = generateReviewToken();',
    '',
    '  const eaccount = nes.eaccount || "";',
    '  const senderConfig = (CONFIG.sender_mapping || {})[eaccount] || null;',
    '  const templateVariables = {',
    '    firstName: caseInput.first_name || null,',
    '    senderName: senderConfig ? senderConfig.sender_name : null,',
    '    bookingLink: senderConfig ? senderConfig.booking_link : null',
    '  };',
    '',
    '  const templateId = decision.reply_template_id || "";',
    '  const blockedVariables = [];',
    '  const replyMode = decision.reply_mode || caseInput.reply_mode || "";',
    '  const sendableMode = replyMode === "FIXED_TEMPLATE_APPROVAL" || replyMode === "AI_DRAFT_APPROVAL";',
    '  if (sendableMode && !templateVariables.senderName) blockedVariables.push("senderName");',
    '  if (/BOOKING|T1_SCENARIO_A|T3_/.test(templateId) && !templateVariables.bookingLink) blockedVariables.push("bookingLink");',
    '',
    '  const sanitizedContext = {',
    '    intake_id: intakeId,',
    '    category: decision.category || caseInput.category || "UNKNOWN",',
    '    confidence: caseInput.confidence ?? decision.confidence ?? null,',
    '    urgency: caseInput.urgency || decision.priority || "routine",',
    '    risk_flags: caseInput.risk_flags || decision.risk_flags || [],',
    '    campaign_context: nes.campaign_context || {},',
    '    reply_subject: reply.subject || null,',
    '    reply_text: reply.text || null,',
    '    reply_snippet: reply.snippet || null,',
    '    recommended_action_plan: decision || {}',
    '  };',
    '',
    '  const draftText = (draft && typeof draft.draft_text === "string") ? draft.draft_text : "";',
    '',
    '  return {',
    '    json: {',
    '      ...input,',
    '      config: CONFIG,',
    '      review_case: {',
    '        case_id: caseId,',
    '        intake_id: intakeId,',
    '        token,',
    '        token_expires_at: expiresIso,',
    '        status: "NEW",',
    '        category: sanitizedContext.category,',
    '        urgency: sanitizedContext.urgency,',
    '        reply_mode: replyMode || "HUMAN_ONLY",',
    '        draft_text: draftText,',
    '        template_variables: templateVariables,',
    '        blocked_variables: blockedVariables,',
    '        sanitized_context: sanitizedContext,',
    '        policy_version: policyVersion,',
    '        kb_version: caseInput.kb_version || CONFIG.kb_version,',
    '        notification_status: "PENDING",',
    '        approver_identity: null,',
    '        approved_at: null,',
    '        final_reply_text: null,',
    '        decision_payload: null,',
    '        created_at: nowIso,',
    '        updated_at: nowIso',
    '      }',
    '    }',
    '  };',
    '});'
  ].join('\n');
}

export function nodeD_GoogleChatPayload() {
  return [
    'const items = $input.all();',
    '',
    'return items.map(item => {',
    '  const input = item.json || {};',
    '  const rc = input.review_case || {};',
    '  const config = input.config || {};',
    '  const ctx = rc.sanitized_context || {};',
    '',
    '  const base = String((config.review || {}).review_base_url || "");',
    '  const reviewUrl = base + "/review?case=" + encodeURIComponent(rc.case_id) + "&token=" + encodeURIComponent(rc.token);',
    '',
    '  const snippet = String(ctx.reply_snippet || ctx.reply_text || "").slice(0, 200);',
    '',
    '  const lines = [];',
    '  lines.push("New reply review case: " + rc.case_id);',
    '  lines.push("Category: " + ctx.category + " | Urgency: " + ctx.urgency);',
    '  lines.push("Reply excerpt: " + snippet);',
    '  lines.push("Review: " + reviewUrl);',
    '',
    '  const chatPayload = { text: lines.join("\\n") };',
    '',
    '  return {',
    '    json: {',
    '      ...input,',
    '      chat_notification: {',
    '        payload: chatPayload,',
    '        review_url: reviewUrl',
    '      }',
    '    }',
    '  };',
    '});'
  ].join('\n');
}

export function nodeD2_NotificationFailed() {
  return [
    'const items = $input.all();',
    '',
    'return items.map(item => {',
    '  const input = item.json || {};',
    '  const rc = { ...(input.review_case || {}) };',
    '  rc.notification_status = "REVIEW_NOTIFICATION_FAILED";',
    '  rc.updated_at = new Date().toISOString();',
    '  return {',
    '    json: {',
    '      ...input,',
    '      review_case: rc,',
    '      chat_notification: { payload: null, review_url: null, skipped_reason: "review.google_chat_configured=false" }',
    '    }',
    '  };',
    '});'
  ].join('\n');
}

export function nodeFMerge_NotificationStatus() {
  return [
    'const items = $input.all();',
    '',
    'return items.map(item => {',
    '  const input = item.json || {};',
    '  const rc = { ...(input.review_case || {}) };',
    '  if (rc.notification_status === "PENDING") {',
    '    const sentOk = !!(input.chat_notification && input.chat_notification.review_url && !input.chat_notification.skipped_reason);',
    '    rc.notification_status = sentOk ? "SENT" : "REVIEW_NOTIFICATION_FAILED";',
    '  }',
    '  rc.updated_at = new Date().toISOString();',
    '  return { json: { ...input, review_case: rc } };',
    '});'
  ].join('\n');
}

export function nodeG_CreateCaseResult() {
  return [
    'const items = $input.all();',
    '',
    'return items.map(item => {',
    '  const input = item.json || {};',
    '  const rc = input.review_case || {};',
    '  return {',
    '    json: {',
    '      case_id: rc.case_id,',
    '      intake_id: rc.intake_id,',
    '      status: rc.status,',
    '      notification_status: rc.notification_status,',
    '      review_notification_failed: rc.notification_status === "REVIEW_NOTIFICATION_FAILED"',
    '    }',
    '  };',
    '});'
  ].join('\n');
}
